jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.3-buster-node
    working_directory: /home/circleci/markdown-clj
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-jars-{{ checksum "project.clj" }}
            - v1-dependency-jars
      - run:
          name: Install Babashka
          command: |
            curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
            chmod +x install
            sudo ./install
      - run: lein test
      - save_cache:
          key: v1-dependency-jars-{{ checksum "project.clj" }}
          paths:
            - /circleci/.m2

workflows:
  version: 2
  build:
    jobs:
      - build
